# datawarehouse:
#   target: dev
#   outputs:
#     dev:
#       type: bigquery
#       method: "{{ env_var('DBT_METHOD') }}" 
#       project: "{{ env_var('DBT_PROJECT') }}"
#       dataset: "{{ env_var('DBT_DATASET') }}"
#       keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"
#       threads: "{{ env_var('DBT_THREADS') | int }}"
#       timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int }}"
#       location: "{{ env_var('DBT_LOCATION') }}"
#       priority: "{{ env_var('DBT_PRIORITY') }}"
#       retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
datawarehouse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account 
      project: dbt-bigquery-442815
      dataset: datasetdbtworkshop
      keyfile: L:\\Documentos\\Luciano Galvao\\meu_data_engineering_roadmap\\workshops\\workshop_DBT\\dbt_bigquery\\datawarehouse\\keyfile.json
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1